---
- name: Install Docker
  amazon.aws.package:
    name: docker
    state: present

- name: Start Docker service
  service:
    name: docker
    state: started
    enabled: true

- name: Build HTMX app container
  community.docker.docker_image:
    path: roles/htmx_app/
    name: htmx_app
    tag: latest

- name: Run HTMX container
  community.docker.docker_container:
    name: htmx_app
    image: htmx_app:latest
    state: started
    ports:
      - "8000:80"
